from enum import StrEnum

class Lokalizacje(StrEnum):
    polska = "Warsaw,PL"
    ukraina = "Kiev,UA"
    belgia = "Brussels,BE"
    niemcy = "Berlin,DE"
    francja = "Paris,FR"
    hiszpania = "Madrid,ES"
    wlochy = "Rome,IT"
    holandia = "Amsterdam,NL"
    austria = "Vienna,AT"
    szwajcaria = "Bern,CH"
    węgry = "Budapest,HU"
    czechy = "Prague,CZ"
    szwecja = "Stockholm,SE"
    norwegia = "Oslo,NO"
    dania = "Copenhagen,DK"
    finlandia = "Helsinki,FI"
    grecja = "Athens,GR"
    portugalia = "Lisbon,PT"
    irlandia = "Dublin,IE"
    cypr = "Nicosia,CY"
    malta = "Valletta,MT"
    litwa = "Vilnius,LT"
    serbia = "Belgrade,RS"
    chorwacja = "Zagreb,HR"
    bosnia = "Sarajevo,BA"
    usa = "Washington,US"
    kanada = "Ottawa,CA"
    australia = "Canberra,AU"
    nowa_zelandia = "Wellington,NZ"
    brazylia = "Brasilia,BR"
    argentyna = "Buenos Aires,AR"
    chile = "Santiago,CL"
    meksyk = "Mexico City,MX"
    kolumbia = "Bogota,CO"
    peru = "Lima,PE"
    urugwaj = "Montevideo,UY"
    paragwaj = "Asuncion,PA"
    panama = "Panama City,PA"
    kuba = "Havana,CU"
    dominikana = "Santo Domingo,DO"
    jordania = "Amman,JO"
    izrael = "Jerusalem,IL"
    irak = "Baghdad,IQ"
    saudi_arabia = "Riyadh,SA"
    egipt = "Cairo,EG"
    maroko = "Rabat,MA"
    tunisja = "Tunis,TN"
    libia = "Tripoli,LY"
    algieria = "Algiers,DZ"
    syria = "Damascus,SY"
    iran = "Tehran,IR"
    japonia = "Tokio,JP"
    
    
def main(x):
    return [item.name for item in x]

if __name__ == "__main__":
    lista_lokalizacji = main(Lokalizacje)
    print(lista_lokalizacji)